services:
  fruit-api-server:
    # command: sh -c 'echo "wait postgres..." && /usr/src/app/wait-for.sh postgres-fruit:3306 -t 36000 -- ./start.sh'
    command: sh -c 'echo "wait postgres(20s)..." && sleep 20 && ./go-api && echo "postgres up!"'
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: fruit-api
    depends_on:
    - postgres-fruit-server
    environment:
    - APP_ENV=example
    ports:
    - 8080:8080
  postgres-fruit-server:
    container_name: postgres-fruit
    environment:
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=fruit
    volumes:
    - ./:/docker-entrypoint-initdb.d
    image: postgres:12.1
    ports:
      - 5436:5432
version: "3"
