database:
  driver: postgres
  connection: host=127.0.0.1 port=5432 user=postgres password=1234 dbname=fruit sslmode=disable
  logger:
    kafka:
      brokers:
        - 127.0.0.1:9092
      topic: sqllog
eventBroker:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: fruit
behaviorLog:
  kafka:
    brokers:
      - 127.0.0.1:9092
    topic: behaviorlog
serviceName: go-api
httpport: 8080